// <auto-generated />
using System;
using EFCoreTask.Core.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240705114519_StudentAndStudentInfoAdded")]
    partial class StudentAndStudentInfoAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTask.Core.Domain.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Royal Villa",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Decent Villa",
                            Price = 400.0
                        });
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.Models.VillaAmanity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaAmanities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pool",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microwave oven",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bed",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Library room",
                            VillaId = 1
                        });
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StudentInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("studentInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("studentInfoId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.StudentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSCMarksPercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StudentInfo");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.Models.VillaAmanity", b =>
                {
                    b.HasOne("EFCoreTask.Core.Domain.Models.Villa", "Villa")
                        .WithMany("villaAmanities")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.Employee", b =>
                {
                    b.HasOne("EFCoreTask.Core.Domain.TaskModel.Employee", "Manager")
                        .WithMany("subordinates")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.Student", b =>
                {
                    b.HasOne("EFCoreTask.Core.Domain.TaskModel.StudentInfo", null)
                        .WithOne("Student")
                        .HasForeignKey("EFCoreTask.Core.Domain.TaskModel.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreTask.Core.Domain.TaskModel.StudentInfo", "studentInfo")
                        .WithMany()
                        .HasForeignKey("studentInfoId");

                    b.Navigation("studentInfo");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.Models.Villa", b =>
                {
                    b.Navigation("villaAmanities");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.Employee", b =>
                {
                    b.Navigation("subordinates");
                });

            modelBuilder.Entity("EFCoreTask.Core.Domain.TaskModel.StudentInfo", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
